---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
- command: /sbin/init
  dockerfile: "../common/update/Containerfile.j2"
  image: ${EDPM_ANSIBLE_MOLECULE_IMAGE:-"ubi9/ubi-init"}
  name: instance
  privileged: true
  registry:
    url: ${EDPM_ANSIBLE_MOLECULE_REGISTRY:-"registry.access.redhat.com"}
  ulimits:
  - host
provisioner:
  log: true
  name: ansible
  inventory:
    hosts:
      all:
        hosts:
          instance:
            canonical_hostname: edpm-0.localdomain
  playbooks:
    prepare: "../common/update/prepare.yml"
    verify: "../common/update/verify.yml"
scenario:
  name: update_without_reload
  test_sequence:
  - dependency
  - destroy
  - create
  - prepare
  - converge
  - verify
  - cleanup
  - destroy
verifier:
  name: ansible
