- name: Enable package repos
  become: true
  ansible.builtin.shell: |
    set -euxo pipefail
    pushd /var/tmp
    curl -sL https://github.com/openstack-k8s-operators/repo-setup/archive/refs/heads/main.tar.gz | tar -xz
    pushd repo-setup-main
    python3 -m venv ./venv
    PBR_VERSION=0.0.0 ./venv/bin/pip install ./
    ./venv/bin/repo-setup current-podified -b antelope
    popd
    rm -rf repo-setup-main
- name: set /etc/localtime
  become: true
  ansible.builtin.file:
    path: /etc/localtime
    src: /usr/share/zoneinfo/UTC
    state: link
- name: set timezone
  ansible.builtin.import_role:
    name: osp.edpm.edpm_timezone
- name: Create firewall directory
  become: true
  ansible.builtin.file:
    path: '/var/lib/edpm-config/firewall'
    state: directory
    owner: root
    group: root
    mode: 0750
- name: open port 22 (edpm_nftables will active this later)
  become: true
  ansible.builtin.copy:
    dest: /var/lib/edpm-config/firewall/sshd-networks.yaml
    content: |
      - rule_name: 003 Allow SSH
        rule:
          proto: tcp
          dport: 22
- name: "Include edpm_users with non default config"
  ansible.builtin.include_role:
    name: "osp.edpm.edpm_users"
  vars:
    edpm_users_users:
      - {"name": "hugetlbfs", "gid": "42477", "group_only": true}
    edpm_users_extra_dirs: []