---
- name: Update openvswitch packages without stopping the service
  become: true
  tags:
    - update
    - ovs
  # Call dnf via the shell module as the ansible dnf module does not
  # support passing --setopt options. This is required in order to disable any
  # OVS rpm scriptlets which would stop and disable OVS services during
  # a standard update. Further info:
  # https://github.com/openstack-k8s-operators/dev-docs/blob/main/ovs-update.md#rpm-packaging
  ansible.builtin.shell: >
    dnf update -y openvswitch --setopt=tsflags=noscripts
  register: update_ovs_result
  changed_when: update_ovs_result.rc == 0
  failed_when: update_ovs_result.rc != 0

  # Reload of openvswitch service will reload OVS systemd services with an automatic
  # restore of already set OpenFlows. Further info:
  # https://github.com/openstack-k8s-operators/dev-docs/blob/main/ovs-update.md#proposal
- name: Reload openvswitch service
  become: true
  tags:
    - reload
    - ovs
  ansible.builtin.systemd_service:
    name: openvswitch.service
    daemon_reload: true
    state: reloaded
    masked: false
  when:
    - edpm_ovs_reload_after_update
    - '"Nothing to do." not in update_ovs_result.stdout_lines'
