---
dependency:
  name: galaxy
driver:
  name: delegated
  options:
    managed: false
    ansible_connection_options:
      ansible_connection: local
platforms:
  - name: compute-1
    groups:
      - compute
provisioner:
  name: ansible
  playbooks:
    prepare: ../common/default/prepare.yml
    cleanup: ../common/cleanup.yml
verifier:
  name: ansible
scenario:
  test_sequence:
    - dependency
    - destroy
    - create
    - prepare
    - converge
    - verify
    - cleanup
    - destroy